### ISSUE TITLE
add support for setQueryData & invalidateQueries

### ISSUE THREAD

**Issue by rayzr522** [sachinraja/trpc-v10-migrate-codemod#20]
i use both of these functions (via `trpc.useContext()`) quite heavily in my project and having to manually migrate them is a pain. shouldn't be too hard to implement migrations for these as they follow more or less the same conventions as `useQuery` and `useMutation`.

v9 -> v10:
- `trpcCtx.setQueryData(['my.query', input], data)` -> `trpcCtx.my.query.setData(data, input)`
- `trpcCtx.invalidateQueries(['my.query', input])` -> `trpcCtx.my.query.invalidate(input)`

the one tricky bit is that the name of the variable housing the trpc context could be... well, anything. in my own codebase it is inconsistent, sometimes `trpcCtx` and sometimes just `ctx`. so my proposal is that, upon encountering `xxx.setQueryData(<pathAndInput>, <data>)` or `xxx.invalidateQueries(<pathAndInput>)`, we just reuse `xxx` and assume that this is the name of the trpc context and that it can be reused. i don't _think_ that should result in too many false positives

**Comment by sachinraja** [comment]
> the one tricky bit is that the name of the variable housing the trpc context could be

I went with the strategy I used for the other "magic" variables and just provided a sensible default (`utils`) and allowed configuration (`--context-namespace`).
