### ISSUE TITLE
queries & mutations with same name overwrite each other

### ISSUE THREAD

**Issue by rayzr522** [sachinraja/trpc-v10-migrate-codemod#21]
i have a few cases in my project where I have both a query & a mutation with the same name. i.e.:
```ts
.query('some-value', ...)
.mutation('some-value', ...)
```
and in these cases, the migration overwrites all but the last procedure. so in those cases I now have only the mutation and the query is just gone

the solution to this is kinda tricky, and I'm not _quite_ familiar enough with the codebase yet to feel confident in my answer. but I believe the only feasible way to do this is:
- do a first pass through the whole codebase to find all the routers
- create a mapping of all the original paths to new normalized path names
- reference that when rewriting both the server & react code

for normalization I'm thinking the least invasive solution is to first `camelCase` everything (as per #18/#19) and _then_ when there's conflicts like this either:
- prefix them with `query` & `mutate` (probably good enough)
- suffix them with numbers (more versatile, leaves onus on devs to rename later, but hey- renaming is ez now! thx v10 💜)

curious to hear your thoughts. I'm not sure quite how versatile you intend this migration tool to be, and if the answer is "well just don't name your queries & mutations the same thing" then... fair. at the end of the day, all I _really_ have to do is just go snag the business logic from a prior commit and migrate these handful of queries myself, so it's nbd

but I think refactoring the path resolution as I described would have overall benefits in terms of versatility of the tool and making it easier to do other normalizations later if need be :)

**Comment by sachinraja** [comment]
> do a first pass through the whole codebase to find all the routers

this does seem like overkill to me. My current strategy is to expose errors so users can fix them, instead of trying to fix all of their problems. Erasing a procedure is definitely not intended though, so I changed it to allow multiple procedures to be on a single path. That's incorrect but you'll have to fix it manually.
