### ISSUE TITLE
Automatically CamelCase things with dots

### ISSUE THREAD

**Issue by KATT** [sachinraja/trpc-v10-migrate-codemod#6]
I'm down to have a stab at fixing this.

It seems like it gets confused when transforming things with dots in it right now.

It would be cool if it did

```ts

const appRouter = router()
	.query('foo.bar', {
		resolve() {
			return 'foo.bar'
		},
	})
	.query('foo.baz', {
		resolve() {
			return 'foo.baz'
		},
	})
```

-->

```ts
t.router({
  fooBar: t.procedure.query(() => 'foo.bar'),
  fooBaz: t.procedure.query(() => 'foo.baz'),
})
```

I've only played with ts morph a little bit before - could you point me in the direction where I could hack around with this?

**Comment by sachinraja** [comment]
Right now it should put those in a nested router (it doesn't get confused, I did this on purpose). Do you think it'd be better to do camelCase?

**Comment by KATT** [comment]
It seems to only pick up the first procedure define on that "sub-router" and delete the rest

**Comment by KATT** [comment]
I'll close this.
