### ISSUE TITLE
Replace wrappers to trpc methods

### ISSUE THREAD

**Issue by jprokay-tb** [sachinraja/trpc-v10-migrate-codemod#92]
We have a a file `utils/trpc.ts` that wraps common v9 functions like so:
```
export const useQuery = trpc.useQuery;
export const useInfiniteQuery = trpc.useInfiniteQuery;
export const useMutation = trpc.useMutation;
export const useUtils = trpc.useContext;
```

Is there a way for code mod to correctly identify & replace instances of `useQuery` for example?

**Comment by sachinraja** [comment]
This is definitely workable. Will try to fix tomorrow. Probably will have it so this works if you set `--react-namespace` to an empty string.

**Comment by jprokay-tb** [comment]
Thanks @sachinraja!
